
(function(){
const $=s=>document.querySelector(s), app=$('#app'), pool=window.QuestionPool, bank=pool.bank;
let engine=null,timerHandle=null,currentResult=null,reviewFilter='all',bankPage=0;
let lang=localStorage.getItem('dsssb-lang')||'en';
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const T=(en,hi)=>lang==='hi'?(hi||en):en;
const qText=q=>T(q.question,q.question_hi);
const qOpts=q=>lang==='hi'&&q.options_hi?.length===4?q.options_hi:q.options;
const qExpl=q=>T(q.explanation,q.explanation_hi);
const qTopic=q=>T(q.topic,q.topic_hi);
const qSection=q=>T(q.section,q.section_hi);
const sylName=s=>T(s.name,s.name_hi);
const sylCoverage=s=>T(s.coverage,s.coverage_hi);
function toggleLang(){lang=lang==='en'?'hi':'en';localStorage.setItem('dsssb-lang',lang);document.documentElement.lang=lang==='hi'?'hi':'en';rerender();}
function langButton(){return `<button class="lang-toggle" data-lang-toggle aria-label="Switch language"><span class="${lang==='en'?'active':''}">EN</span><span>/</span><span class="${lang==='hi'?'active':''}">हिं</span></button>`}
function bindLang(){document.querySelectorAll('[data-lang-toggle]').forEach(b=>b.onclick=toggleLang)}
function rerender(){if(engine){renderQuestion();tick();return}if(currentResult){renderResults(currentResult);return}renderBankPage()}
function fmtTime(sec){sec=Math.max(0,Math.floor(sec));const h=Math.floor(sec/3600),m=Math.floor((sec%3600)/60),s=sec%60;return h?`${h}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`:`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`}
function sectionOptions(all=true){return (all?`<option value="ALL">${T('All sections','सभी खंड')}</option>`:'')+bank.syllabus.map(s=>`<option value="${s.id}">${s.id} · ${esc(sylName(s))}</option>`).join('')}
function home(){stopTimer();engine=null;currentResult=null;const active=loadActive();app.innerHTML=`<div class="shell"><div class="lang-row">${langButton()}</div><section class="hero"><div class="hero-card"><div class="eyebrow">${T('POST CODE 24/26 · SUBJECT CONCERNED','पोस्ट कोड 24/26 · विषय संबंधित')}</div><h1>${T('JSA Lie-Detection','JSA लाई-डिटेक्शन')}<br>${T('Mock Test Lab','मॉक टेस्ट लैब')}</h1><p>${T(`Practice the complete uploaded syllabus with ${bank.metadata.questionCount.toLocaleString()} original MCQs, balanced subject mocks, explanations, negative marking, revision filters and section analytics.`,`अपलोड किए गए पूर्ण पाठ्यक्रम का ${bank.metadata.questionCount.toLocaleString()} MCQs, संतुलित मॉक टेस्ट, व्याख्या, नकारात्मक अंकन, पुनरावृत्ति फ़िल्टर और खंड-वार विश्लेषण के साथ अभ्यास करें।`)}</p><div class="cta-row"><button class="primary" data-action="random100">${T('Start random 100-Q mock','रैंडम 100-प्रश्न मॉक शुरू करें')}</button><button class="secondary" data-action="bank">${T('Browse question bank','प्रश्न बैंक देखें')}</button></div>${active?`<div class="resume"><div><strong>${T('Unfinished test found','अधूरा टेस्ट मिला')}</strong><div class="small-note">${esc(active.title)} · ${Object.keys(active.answers||{}).length}/${active.questionIds.length} ${T('answered','उत्तर दिए')}</div></div><button class="primary" data-action="resume">${T('Resume','जारी रखें')}</button></div>`:''}</div><div class="card stats-grid"><div class="stat"><b>${bank.metadata.questionCount.toLocaleString()}</b><span>${T('Question database','प्रश्न डेटाबेस')}</span></div><div class="stat"><b>${bank.metadata.mockCount}</b><span>${T('Balanced mocks','संतुलित मॉक')}</span></div><div class="stat"><b>${bank.metadata.sectionCount}</b><span>${T('Syllabus sections','पाठ्यक्रम खंड')}</span></div><div class="stat"><b>-0.25</b><span>${T('Negative marking','नकारात्मक अंकन')}</span></div></div></section>
<div class="section-title"><div><h2>${T('Practice modes','अभ्यास मोड')}</h2><p>${T('Everything runs in the browser; no login or backend is required.','सब कुछ ब्राउज़र में चलता है; लॉगिन या बैकएंड की आवश्यकता नहीं है।')}</p></div></div><section class="grid"><div class="card mode-card"><div class="eyebrow">${T('EXAM MODE','परीक्षा मोड')}</div><h3>${T('Balanced subject mock','संतुलित विषय मॉक')}</h3><p>${T('100 questions, 10 from each syllabus section, 60-minute subject-practice timer and -0.25 negative marking.','100 प्रश्न, प्रत्येक पाठ्यक्रम खंड से 10 प्रश्न, 60 मिनट का टाइमर और -0.25 नकारात्मक अंकन।')}</p><button class="primary" data-action="random100">${T('Generate mock','मॉक बनाएं')}</button></div><div class="card mode-card"><div class="eyebrow">${T('TARGETED MODE','लक्षित मोड')}</div><h3>${T('Custom practice','कस्टम अभ्यास')}</h3><p>${T('Choose a section, difficulty and question count to focus on weak areas.','कमजोर क्षेत्रों पर ध्यान देने के लिए खंड, कठिनाई और प्रश्न संख्या चुनें।')}</p><button class="secondary" data-action="custom-scroll">${T('Configure below','नीचे सेट करें')}</button></div><div class="card mode-card"><div class="eyebrow">${T('REVISION MODE','पुनरावृत्ति मोड')}</div><h3>${T('Search all questions','सभी प्रश्न खोजें')}</h3><p>${T('Filter the complete bank by keyword, section or difficulty and reveal the answer with explanation.','पूर्ण बैंक को कीवर्ड, खंड या कठिनाई के अनुसार फ़िल्टर करें और उत्तर व व्याख्या देखें।')}</p><button class="secondary" data-action="bank">${T('Open bank','बैंक खोलें')}</button></div></section>
<div class="section-title"><div><h2>${T('30 fixed mock tests','30 निर्धारित मॉक टेस्ट')}</h2><p>${T('Across Mocks 01–30, every question in the 3,000-question database is used exactly once.','मॉक 01–30 में 3,000 प्रश्नों के डेटाबेस का प्रत्येक प्रश्न एक बार उपयोग होता है।')}</p></div></div><section class="mock-grid">${bank.mocks.map(m=>`<button class="mock-btn" data-mock="${m.mockId}"><strong>${T(m.mockId.replace('LD-MOCK-','Mock '),m.mockId.replace('LD-MOCK-','मॉक '))}</strong><span>100 Q · 60 min</span></button>`).join('')}</section>
<div class="section-title" id="custom"><div><h2>${T('Custom practice builder','कस्टम अभ्यास निर्माता')}</h2><p>${T('Use one section at a time or the complete bank.','एक समय में एक खंड या पूरा बैंक उपयोग करें।')}</p></div></div><section class="card setup"><div class="form-grid"><div class="field"><label>${T('Section','खंड')}</label><select id="custom-section">${sectionOptions()}</select></div><div class="field"><label>${T('Difficulty','कठिनाई')}</label><select id="custom-diff"><option value="ALL">${T('All difficulties','सभी कठिनाइयाँ')}</option><option>Easy</option><option>Medium</option><option>Hard</option></select></div><div class="field"><label>${T('Questions','प्रश्न')}</label><select id="custom-count"><option>25</option><option>50</option><option selected>100</option><option>150</option><option>300</option></select></div><div class="field"><label>${T('Timer (minutes)','टाइमर (मिनट)')}</label><input id="custom-min" type="number" min="5" max="240" value="60"></div></div><div class="actions" style="margin-top:14px"><button class="primary" data-action="custom-start">${T('Start custom test','कस्टम टेस्ट शुरू करें')}</button></div></section>
<div class="section-title"><div><h2>${T('Syllabus coverage','पाठ्यक्रम कवरेज')}</h2><p>${T('300 questions in each official heading.','प्रत्येक आधिकारिक शीर्षक में 300 प्रश्न।')}</p></div></div><section class="grid">${bank.syllabus.map(s=>`<div class="card mode-card"><div class="eyebrow">${s.id} · 300 ${T('QUESTIONS','प्रश्न')}</div><h3>${esc(sylName(s))}</h3><p>${esc(sylCoverage(s))}</p><button class="secondary" data-section-start="${s.id}">${T('Practice','अभ्यास')} ${s.id}</button></div>`).join('')}</section></div>`; bindHome();bindLang()}
function bindHome(){app.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>{const a=b.dataset.action;if(a==='random100')startTest('RANDOM-'+Date.now(),T('Random balanced 100-Q mock','रैंडम संतुलित 100-प्रश्न मॉक'),pool.balancedRandom(100),60);if(a==='bank')renderBank();if(a==='custom-scroll')$('#custom').scrollIntoView({behavior:'smooth'});if(a==='custom-start'){const sid=$('#custom-section').value,d=$('#custom-diff').value,n=+$('#custom-count').value,min=+$('#custom-min').value;const qs=pool.customQuestions({sections:[sid],difficulty:d,count:n});startTest('CUSTOM-'+Date.now(),`${sid==='ALL'?T('All sections','सभी खंड'):sid} ${T('custom practice','कस्टम अभ्यास')}`,qs,min)}if(a==='resume')resumeTest()});app.querySelectorAll('[data-mock]').forEach(b=>b.onclick=()=>{const m=bank.mocks.find(x=>x.mockId===b.dataset.mock);startTest(m.mockId,m.title,pool.questionsForMock(m.mockId),m.recommendedMinutes)});app.querySelectorAll('[data-section-start]').forEach(b=>b.onclick=()=>{const sid=b.dataset.sectionStart;startTest('SECTION-'+sid+'-'+Date.now(),`${sid} ${T('targeted practice','लक्षित अभ्यास')}`,pool.customQuestions({sections:[sid],count:100}),60)})}
function startTest(id,title,questions,minutes,resumeState=null){stopTimer();engine=new TestEngine({id,title,questions,minutes,marking:bank.metadata.marking,resumeState});engine.save();renderQuestion();timerHandle=setInterval(tick,1000);tick()}
function loadActive(){try{return JSON.parse(localStorage.getItem('dsssb-active-test')||'null')}catch{return null}}
function resumeTest(){const s=loadActive();if(!s)return home();const qs=s.questionIds.map(id=>pool.byId.get(id)).filter(Boolean);if(!qs.length){localStorage.removeItem('dsssb-active-test');return home()}startTest(s.id,s.title,qs,s.minutes,s)}
function renderQuestion(){if(!engine)return;const q=engine.questions[engine.index],ans=engine.answers[q.id];const counts=engine.counts(),opts=qOpts(q);app.innerHTML=`<div class="shell"><div class="testbar"><div><div class="eyebrow">${esc(engine.title)}</div><div class="test-meta"><span class="pill">${counts.answered}/${engine.questions.length} ${T('answered','उत्तर दिए')}</span><span class="pill">${counts.marked} ${T('marked','चिह्नित')}</span><span class="pill">+1 / -0.25</span></div></div><div class="timer-tools">${langButton()}<div class="timer" id="timer">--:--</div></div></div><div class="test-layout"><section class="test-main"><div class="card question-card"><div class="q-head"><div class="q-number">${T('Question','प्रश्न')} ${engine.index+1} ${T('of','में से')} ${engine.questions.length}</div><div class="q-tags"><span class="tag">${q.section_id}</span><span class="tag">${esc(qTopic(q))}</span><span class="tag">${esc(T(q.difficulty,q.difficulty==='Easy'?'सरल':q.difficulty==='Medium'?'मध्यम':'कठिन'))}</span></div></div><div class="question-text">${esc(qText(q))}</div><div class="options">${opts.map((o,i)=>`<button class="option ${ans===i?'selected':''}" data-opt="${i}"><span class="letter">${'ABCD'[i]}</span><span>${esc(o)}</span></button>`).join('')}</div><div class="q-actions"><div class="left"><button class="ghost" data-nav="prev" ${engine.index===0?'disabled':''}>← ${T('Previous','पिछला')}</button><button class="secondary" data-act="clear">${T('Clear response','उत्तर साफ करें')}</button><button class="secondary" data-act="mark">${engine.marked[q.id]?T('Unmark review','रिव्यू हटाएँ'):T('Mark for review','रिव्यू हेतु चिह्नित करें')}</button></div><div class="right"><button class="primary" data-nav="next">${engine.index===engine.questions.length-1?T('Save','सहेजें'):T('Save & next','सहेजें और अगला')} →</button></div></div></div></section><aside class="card palette-card"><div class="palette-title"><b>${T('Question palette','प्रश्न पैलेट')}</b><span class="small-note">${counts.unattempted} ${T('left','शेष')}</span></div><div class="palette">${engine.questions.map((x,i)=>`<button class="pbtn ${engine.answers[x.id]!==undefined?'answered':''} ${engine.marked[x.id]?'marked':''} ${i===engine.index?'current':''}" data-jump="${i}">${i+1}</button>`).join('')}</div><div class="legend"><span><i class="dot a"></i>${T('Answered','उत्तरित')}</span><span><i class="dot m"></i>${T('Review','रिव्यू')}</span></div><div class="progressbar"><span style="width:${counts.answered/engine.questions.length*100}%"></span></div><button class="danger submit-wide" data-submit>${T('Submit test','टेस्ट जमा करें')}</button></aside></div></div>`;
bindLang();app.querySelectorAll('[data-opt]').forEach(b=>b.onclick=()=>{engine.answer(engine.index,+b.dataset.opt);renderQuestion();tick()});app.querySelectorAll('[data-jump]').forEach(b=>b.onclick=()=>{engine.index=+b.dataset.jump;engine.save();renderQuestion();tick()});app.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>{if(b.dataset.nav==='prev')engine.index=Math.max(0,engine.index-1);else engine.index=Math.min(engine.questions.length-1,engine.index+1);engine.save();renderQuestion();tick()});app.querySelector('[data-act="clear"]').onclick=()=>{engine.clear(engine.index);renderQuestion();tick()};app.querySelector('[data-act="mark"]').onclick=()=>{engine.toggleMark(engine.index);renderQuestion();tick()};app.querySelector('[data-submit]').onclick=confirmSubmit}
function tick(){if(!engine)return;const el=$('#timer');if(!el)return;const ms=engine.remainingMs();el.textContent=fmtTime(ms/1000);el.classList.toggle('low',ms<=300000);if(ms<=0){stopTimer();currentResult=engine.submit();renderResults(currentResult)}}
function stopTimer(){if(timerHandle){clearInterval(timerHandle);timerHandle=null}}
function confirmSubmit(){const c=engine.counts(),dlg=$('#confirm');$('#confirm-title').textContent=T('Submit this test?','क्या यह टेस्ट जमा करना है?');$('#confirm-copy').textContent=T(`Answered ${c.answered} of ${engine.questions.length}. ${c.unattempted} questions are unattempted. Once submitted, this attempt is locked.`,`${engine.questions.length} में से ${c.answered} प्रश्नों के उत्तर दिए गए हैं। ${c.unattempted} प्रश्न अनुत्तरित हैं। जमा करने के बाद यह प्रयास लॉक हो जाएगा।`);dlg.showModal();dlg.addEventListener('close',function once(){dlg.removeEventListener('close',once);if(dlg.returnValue==='submit'){stopTimer();currentResult=engine.submit();renderResults(currentResult)}})}
function renderResults(r){stopTimer();const angle=Math.max(0,Math.min(360,(r.score/r.max)*360));app.innerHTML=`<div class="shell"><div class="lang-row">${langButton()}</div><section class="card result-hero"><div><div class="score-ring" style="--score-angle:${angle}deg"><div><b>${r.score.toFixed(2)}</b><span>${T('out of','में से')} ${r.max}</span></div></div></div><div><div class="eyebrow">${T('TEST RESULT','टेस्ट परिणाम')}</div><h1 style="margin:7px 0 16px">${esc(r.title)}</h1><div class="result-kpis"><div class="kpi"><b class="ok">${r.correct}</b><span>${T('Correct','सही')}</span></div><div class="kpi"><b class="bad">${r.wrong}</b><span>${T('Wrong','गलत')}</span></div><div class="kpi"><b>${r.unattempted}</b><span>${T('Unattempted','अनुत्तरित')}</span></div><div class="kpi"><b>${r.accuracy.toFixed(1)}%</b><span>${T('Accuracy','शुद्धता')}</span></div></div><div class="actions no-print" style="margin-top:16px"><button class="primary" data-result="review">${T('Review answers','उत्तर समीक्षा')}</button><button class="secondary" data-result="print">${T('Print / Save PDF','प्रिंट / PDF सहेजें')}</button><button class="secondary" data-result="home">${T('Dashboard','डैशबोर्ड')}</button></div><div class="small-note" style="margin-top:10px">${T('Time used','लगा समय')}: ${fmtTime(r.timeSeconds)} · ${T('Marking','अंकन')}: +1 / -0.25.</div></div></section><div class="section-title"><div><h2>${T('Section analytics','खंड-वार विश्लेषण')}</h2><p>${T('Use this to identify weak syllabus areas.','कमजोर पाठ्यक्रम क्षेत्रों की पहचान हेतु इसका उपयोग करें।')}</p></div></div><section class="card table-wrap"><table class="analysis-table"><thead><tr><th>${T('Section','खंड')}</th><th>${T('Correct','सही')}</th><th>${T('Wrong','गलत')}</th><th>${T('Unattempted','अनुत्तरित')}</th><th>${T('Accuracy','शुद्धता')}</th></tr></thead><tbody>${r.sections.map(s=>{const att=s.correct+s.wrong;const src=bank.syllabus.find(x=>x.id===s.id);return`<tr><td><b>${s.id}</b> · ${esc(src?sylName(src):s.section)}</td><td class="ok">${s.correct}</td><td class="bad">${s.wrong}</td><td>${s.unattempted}</td><td>${att?(s.correct/att*100).toFixed(1):'0.0'}%</td></tr>`}).join('')}</tbody></table></section></div>`;bindLang();app.querySelectorAll('[data-result]').forEach(b=>b.onclick=()=>{if(b.dataset.result==='review')renderReview(r);if(b.dataset.result==='print')window.print();if(b.dataset.result==='home')home()})}
function renderReview(r){currentResult=r;const ids=r.questionIds,ans=r.answers;const items=ids.map(id=>pool.byId.get(id)).filter(Boolean);const filtered=items.filter(q=>{if(reviewFilter==='all')return true;const a=ans[q.id];if(reviewFilter==='wrong')return a!==undefined&&a!==q.correctIndex;if(reviewFilter==='unattempted')return a===undefined;if(reviewFilter==='correct')return a===q.correctIndex;return true});app.innerHTML=`<div class="shell"><div class="section-title"><div><h2>${T('Answer review','उत्तर समीक्षा')}</h2><p>${filtered.length} ${T('questions shown.','प्रश्न दिखाए गए।')}</p></div><div class="actions no-print">${langButton()}<select id="review-filter"><option value="all">${T('All','सभी')}</option><option value="wrong">${T('Wrong only','केवल गलत')}</option><option value="unattempted">${T('Unattempted','अनुत्तरित')}</option><option value="correct">${T('Correct only','केवल सही')}</option></select><button class="secondary" id="review-back">${T('Back to result','परिणाम पर वापस')}</button></div></div><div class="review-list">${filtered.map(q=>{const a=ans[q.id],opts=qOpts(q);return`<article class="card review-item"><div class="eyebrow">${q.id} · ${q.section_id} · ${esc(qTopic(q))}</div><h4>${esc(qText(q))}</h4><div class="review-options">${opts.map((o,i)=>`<div class="${i===q.correctIndex?'correct':(a===i?'wrong':'')}">${'ABCD'[i]}. ${esc(o)} ${i===q.correctIndex?'✓':''} ${a===i&&i!==q.correctIndex?T('← your answer','← आपका उत्तर'):''}</div>`).join('')}</div><div class="explanation"><b>${T('Explanation','व्याख्या')}:</b> ${esc(qExpl(q))}</div></article>`}).join('')}</div></div>`;bindLang();$('#review-filter').value=reviewFilter;$('#review-filter').onchange=e=>{reviewFilter=e.target.value;renderReview(r)};$('#review-back').onclick=()=>renderResults(r)}
function renderBank(){stopTimer();engine=null;currentResult=null;bankPage=0;renderBankPage()}
function renderBankPage(){const qv=$('#bank-query')?.value||'',sec=$('#bank-sec')?.value||'ALL',dif=$('#bank-diff')?.value||'ALL';const data=pool.filterQuestions({section:sec,difficulty:dif,query:qv}),pageSize=20,pages=Math.max(1,Math.ceil(data.length/pageSize));bankPage=Math.min(bankPage,pages-1);const page=data.slice(bankPage*pageSize,(bankPage+1)*pageSize);app.innerHTML=`<div class="shell"><div class="section-title"><div><h2>${T('Question bank','प्रश्न बैंक')}</h2><p>${T('Search and revise all','सभी को खोजें और दोहराएँ')} ${bank.metadata.questionCount.toLocaleString()} ${T('items.','प्रश्न।')}</p></div><div class="actions">${langButton()}<button class="secondary" id="bank-home">${T('Dashboard','डैशबोर्ड')}</button></div></div><section class="card filters"><input id="bank-query" placeholder="${T('Search question, answer, explanation or topic','प्रश्न, उत्तर, व्याख्या या विषय खोजें')}" value="${esc(qv)}"><select id="bank-sec">${sectionOptions()}</select><select id="bank-diff"><option value="ALL">${T('All difficulties','सभी कठिनाइयाँ')}</option><option>Easy</option><option>Medium</option><option>Hard</option></select><button class="primary" id="bank-search">${T('Search','खोजें')}</button></section><div class="small-note" style="margin:10px 2px">${data.length.toLocaleString()} ${T('matching questions','मिलते प्रश्न')} · ${T('page','पृष्ठ')} ${bankPage+1} ${T('of','में से')} ${pages}</div><div class="bank-list">${page.length?page.map(q=>{const opts=qOpts(q);return`<article class="card bank-item"><div class="eyebrow">${q.id} · ${q.section_id} · ${esc(qTopic(q))} · ${q.difficulty}</div><h3>${esc(qText(q))}</h3><div class="small-note">A. ${esc(opts[0])}<br>B. ${esc(opts[1])}<br>C. ${esc(opts[2])}<br>D. ${esc(opts[3])}</div><details><summary>${T('Show answer & explanation','उत्तर और व्याख्या दिखाएँ')}</summary><div class="explanation"><b>${q.correctOption}. ${esc(opts[q.correctIndex])}</b><br>${esc(qExpl(q))}</div></details></article>`}).join(''):'<div class="card empty">'+T('No questions match these filters.','इन फ़िल्टरों से कोई प्रश्न नहीं मिला।')+'</div>'}</div><div class="actions" style="justify-content:center;margin-top:16px"><button class="secondary" id="bank-prev" ${bankPage===0?'disabled':''}>← ${T('Previous','पिछला')}</button><button class="secondary" id="bank-next" ${bankPage>=pages-1?'disabled':''}>${T('Next','अगला')} →</button></div></div>`;bindLang();$('#bank-sec').value=sec;$('#bank-diff').value=dif;$('#bank-home').onclick=home;$('#bank-search').onclick=()=>{bankPage=0;renderBankPage()};$('#bank-query').onkeydown=e=>{if(e.key==='Enter'){bankPage=0;renderBankPage()}};$('#bank-prev').onclick=()=>{bankPage--;renderBankPage()};$('#bank-next').onclick=()=>{bankPage++;renderBankPage()}}
$('#home-brand').onclick=home;$('#reset-storage').onclick=()=>{if(confirm(T('Delete saved test progress and last result from this browser?','क्या इस ब्राउज़र से सहेजी गई टेस्ट प्रगति और अंतिम परिणाम हटाना है?'))){localStorage.removeItem('dsssb-active-test');localStorage.removeItem('dsssb-last-result');home()}};
if('serviceWorker' in navigator && location.protocol.startsWith('http'))navigator.serviceWorker.register('./sw.js').catch(()=>{});
document.documentElement.lang=lang==='hi'?'hi':'en';
function startRandomOnOpen(){localStorage.removeItem('dsssb-active-test');const questions=pool.balancedRandom(100);startTest('AUTO-RANDOM-'+Date.now(),T('Auto-generated random balanced 100-Q mock','स्वतः निर्मित रैंडम संतुलित 100-प्रश्न मॉक'),questions,60)}
startRandomOnOpen();
})();
